<a href="https://colab.research.google.com/github/Shivanikumari0809/Shivani_BigData/blob/main/assignment2_5-feb_202301060.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


arr1 = np.array([1, 2, 3, 6, 4, 5])

result = np.flip(arr1)


print("final array", str(result))


final array [5 4 6 3 2 1]


In [2]:
import numpy as np


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

arr_equal = np.array_equal(arr1, arr2)

if arr_equal:
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")

Arrays are equal.


In [5]:
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])

counts = np.bincount(x)
most_fre_value = counts.argmax()
indices = np.where(x == most_fre_value)[0]

print(f"Most fre value: {most_frequent_value}")
print(f"Indices: {indices}")
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

counts = np.bincount(y)
most_frequent_value = counts.argmax()
indices = np.where(y == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

Most fre value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


In [6]:
import numpy as np

x = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(x)

sum_matrix = np.sum(x)
print("\n the sum of matrix is", sum_matrix)

sum_row = x.sum(axis = 1)
print("\n the sum of all rows are:", sum_row)

sum_col = x.sum(axis = 0)
print("\n the sum of all columns are:", sum_col)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

 the sum of matrix is 45

 the sum of all rows are: [[14]
 [16]
 [15]]

 the sum of all columns are: [[20  9 16]]
